enum PageTitles {
    HOME = "Bảng điều khiển - UEF",
    BM = "Biểu mẫu - UEF",
    BM01 = "Biểu mẫu 01: Chủ nhiệm lớp - UEF",
    BM02 = "Biểu mẫu 02: Cố vấn học tập, trợ giảng, phụ đạo - UEF",
    BM03 = "Biểu mẫu 03: Tư vấn tuyển sinh - UEF",
    BM04 = "Biểu mẫu 04: Hỏi vấn đáp Tiếng Anh - UEF",
    BM05 = "Biểu mẫu 05: Biểu mẫu BGH phê duyệt - UEF",
    BM13 = "Biểu mẫu 13: Nội quy giảng dạy - UEF",
    BM15 = "Biểu mẫu 15: Nội quy lao động - UEF",
    SUMMARY_ACTIVITIES = "Tổng kết hoạt động - UEF",
    LOGS_ACTIVITY = "Lịch sử hoạt động - UEF",
    SEARCH = "Tra cứu CB-GV-NV - UEF",
    APPLICATIONS = "Ứng dụng - UEF",
    ROLES = "Vai trò - UEF",
    PERMISSIONS = "Phân quyền - UEF",
    MENUS = "Chức năng - UEF",
    SCHOOL_YEARS = "Thời gian năm học - UEF",
    UNITS = "Đơn vị - UEF",
    NOT_FOUND = "Không tìm thấy trang - UEF",
    NOT_PERMISSIONS = "Từ chối truy cập - UEF",
    WORKLOAD_GROUPS = "Nhóm biểu mẫu - UEF",
    DOCUMENTS = "Quản lý văn bản - UEF",
}

export default PageTitles;